### ISSUE TITLE
Need to update hiredis dependency for ruby 2.2.x?

### ISSUE THREAD

**Issue by dopin** [whoahbot/dm-redis-adapter#61]
Hi. I hit `undefined symbol: rb_thread_select` error on ruby 2.2.0 with hiredis v0.4.5.
It seems that ruby 2.2.x removed rb_thread_select and hiredis supports it since v0.6.0.
https://github.com/redis/hiredis-rb/commit/f85e8c65f70f2ab27e10caa18b294c8c43f1d0f6

I'm sorry if I'm doing something wrong. Thanks.

**Comment by toshhub** [comment]
Hi dopin,
I also got the same error.
If the error still persists, then try changing the version of the redis and hiredis gem to the latest. It solved the problem for me.

**Comment by nordringrayhide** [comment]
+1

**Comment by thebadmonkeydev** [comment]
:+1: I have this issue as well

**Comment by factyahagi** [comment]
:+1: I also got the same error.

**Comment by yasu** [comment]
👍

**Comment by abriel** [comment]
+1
